name: Keep Render Awake

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping health endpoint
        env:
          URL: ${{ secrets.RENDER_HEALTH_URL }}
        run: |
          curl -sS -m 10 --retry 2 --retry-max-time 20 -o /dev/null "$URL"
